# Generated by Django 5.0 on 2024-01-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_alter_coffee_discription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coffee',
            old_name='quality',
            new_name='quantity',
        ),
        migrations.AlterField(
            model_name='coffee',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
